### ISSUE TITLE
Email domain should be independent from custom domain

### ISSUE THREAD

**Issue by the-architect** [TryGhost/Members#109]
Hi,

I am trialing your hosted Ghost atm and ran into this issue that I can't change the email from to a custom one. There I also saw that you are using the www.domain.com as the from domain.

I think this should be independent, due to the restrictions you have with custom domains and CNAMEs.

Either make the email address completely custom without the restriction to the domain that was set up or remove the www in front of the domain leading to weird looking email addresses like: newsletter@www.mydomain.com

Cheers :)

**Comment by piotrkundu** [comment]
@the-architect True that. The blog url has nothing to do with how you set up your email domains.

**Comment by allouis** [comment]
This is tracked here: https://github.com/TryGhost/Ghost/issues/11414
